apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-dpl
  namespace: deploy-argocd
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: gitops-demo
          image: datngxtiens/gitops-demo:13
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: deploy-argocd
spec:
  selector:
    app: demo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30398
